---
title: "bundesliga2324_subs"
output: html_document
---

```{r, setup}
library("worldfootballR")
library("dplyr")
library("ggplot2")
```

```{r}
## Load summary data
match_summary <- load_fb_match_summary(
  country = "GER",
  gender = "M",
  tier = "1st",
  season_end_year = 2025
)

substitutions <- match_summary |>
  filter(Event_Type == "Substitute")
head(
  substitutions |>
    select(
      Match_Date,
      Home_Team,
      Away_Team,
      Team,
      Event_Players,
      Event_Time,
      Score_Progression
    )
)
# Plot rel frequency of substitutions times
substitutions |>
  ggplot(aes(x = Event_Time)) +
  geom_histogram(binwidth = 1) +
  labs(
    x = "minute",
    y = "number of substitutions"
  ) +
  theme_bw()

## Extract players of PLAYER
substitutions <- substitutions |>
  mutate(
    player_in = stringr::str_remove(Event_Players, " for .*$"),
    player_out = stringr::str_remove(Event_Players, "^.* for ")
  )
# Clean substitutions
substitutions <- substitutions |>
  mutate(
    player_in = case_when(
      player_in == "Aliou Baldé" ~ "Aliou Badara Baldé",
      player_in == "Marcus Kristensen" &
        Team == "Stuttgart" &
        Match_Date == "2024-12-21" ~ "Jarzinho Malanga",
      .default = player_in
    )
  )

player_in <- substitutions |>
  select(MatchURL, player_in, Team)
head(player_in[, -1])
```

```{r}
## Load lineups
advanced <- load_fb_advanced_match_stats(
  country = "GER",
  gender = "M",
  tier = "1st",
  stat_type = "summary",
  team_or_player = "player",
  season_end_year = "2025"
)

```
```{r}
## Merge both datasets and keep only players from the starting lineup
starters <- advanced |>
  anti_join(
    y = player_in,
    by = c("MatchURL", "Team", "Player" = "player_in")
  )
```

```{r}
## Sanity check
no_of_players <- starters |>
  group_by(MatchURL, Team) |>
  count() |>
  ungroup() |>
  pull(n)
all.equal(length(no_of_players[no_of_players != 11]), 0)
```

```{r}
# Construct survival data
sub_events <- substitutions |>
  select(
    MatchURL,
    Team,
    Player = player_out,
    sub_time = Event_Time
  )


starter_sub_events <- sub_events |>
  semi_join(
    y = starters,
    by = c("MatchURL", "Team", "Player")
  )

